name: stego
channels:
  - pytorch
  - anaconda
  - conda-forge
  - menpo
dependencies:
  - opencv=4.5.5
  - pip
  - python=3.10.4
  - pytorch=1.13.1
  - pytorch-lightning=1.9.4
  - scikit-image=0.19.2
  - torchvision=0.14.1
  - pip:
      - easydict==1.10
      - future==0.18.3
      - hydra-core==1.3.2
      - kornia==0.6.10
      - matplotlib==3.7.1
      - mypy==1.1.1
      - numpy==1.24.2
      - pandas==1.5.3
      - psutil==5.9.4
      - pydensecrf @ git+https://github.com/lucasb-eyer/pydensecrf.git
      - pydeprecate==0.3.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - setuptools==67.6.0
      - tensorboard==2.12.0
      - torchpq==0.3.0.5
      - tqdm==4.65.0
      - types-pillow==9.4.0.17
      - types-tqdm==4.65.0.0
      - wget==3.2
