channels:
- anaconda
- pytorch
- conda-forge
- menpo
dependencies:
- python=3.9
- pip
- pytorch
- torchvision
- torchaudio
  # - cudatoolkit=11.0
  # - nvidia-apex==0.1.0
- scikit-image
- opencv
  # - cupy
- pytorch-lightning
- pip:
  - matplotlib
  - psutil
  - tqdm
  - pandas
  - scipy
  - numpy
  - tensorboard
  - future
  - --find-links https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
  - kornia
  - hydra-core
  - wget
  - seaborn
  - easydict
  - torchpq
  - git+https://github.com/lucasb-eyer/pydensecrf.git
  - setuptools
  - pyDeprecate
  - cython
name: stego
