# base_config has common preferences for all configs
defaults:
  - base_config
  - _self_

model_path: "../saved_models/cocostuff27_vit_base_5.ckpt"
image_dir: "/datadrive/pytorch-data/cocostuff/images/val2017"
experiment_name: "cocostuff_val"
res: 320
batch_size: 8
use_ddp: False
