# only used in crop_datasets.py and precompute_knns.py
crop_knn:
  dataset_names:
    - cityscapes
  image_sets:
    - train
    - val
  crop_types:
    - five
  crop_ratios:
    - 0.5


# dataset_name: "cityscapes"

# Cityscapes
train:
  neg_inter_weight: .72
  pos_inter_weight: .18
  pos_intra_weight: .46
  neg_inter_shift: .25
  pos_inter_shift: .20
  pos_intra_shift: .25

  # Cityscapes 10/3
  #neg_inter_weight: 0.9058762625226623
  #pos_inter_weight: 0.577453483136995
  #pos_intra_weight: 1
  #neg_inter_shift: 0.31361241889448443
  #pos_inter_shift: 0.1754346515479633
  #pos_intra_shift: 0.45828472207

  log_dir: "cityscapes"
  dataset_name: "cityscapes"
