# only used in crop_datasets.py and precompute_knns.py
crop_knn:
  dataset_names:
    - potsdam
  image_sets:
    - train
    - val
  crop_types:
    - five
    - null
  crop_ratios:
    - 0.5

# dataset_name: "potsdam"

train:
  # Potsdam vit small 1/31/22
  neg_inter_weight: 0.63
  pos_inter_weight: 0.25
  pos_intra_weight: 0.67
  neg_inter_shift: 0.46
  pos_inter_shift: 0.02
  pos_intra_shift: 0.08

  log_dir: "potsdam"
  datset_name: "potsdam"
